version: "3"

http:
  address: 0.0.0.0:8082
  middleware: [ ]
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  worker:
    command: "php"
    args:
      - "src/simple_worker.php"
    relay: "pipes"

logs:
  mode: development
  level: debug
  output: stdout
  err_output: stderr
  encoding: json

