version: "3"

server:
  command: "php src/test_worker.php"

http:
  address: 0.0.0.0:8082
  pool:
    num_workers: 4
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

logs:
  mode: production
  level: info
  output: stdout
  err_output: stderr
