version: "3"

http:
  address: 0.0.0.0:8082
  middleware: [ ]
  pool:
    num_workers: 4
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  worker:
    command: "php src/worker.php"
    relay: "pipes"

logs:
  mode: production
  level: info
  output: stdout
  err_output: stderr
